{% set version = "1.0.0" %}
{% set name = "mmvec" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d1a69bcf356fa59af299e0fa43f7093ab9bc87548ec36b8bd78b88f4351e953c


build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - qiime2.plugins = mmvec.q2.plugin_setup:plugin

requirements:
  host:
    - python >=3
    - pip

  run:
    - python >=3
    - pandas
    - click
    - tensorflow >1.7
    - scikit-bio >0.5.4
    - seaborn
    - scikit-learn
    - tqdm
    - h5py
    - mock
    - biom-format

test:
  imports:
    - mmvec

about:
  home: https://github.com/biocore/mmvec
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Neural networks for microbe-metabolite interaction analysis'

extra:
  recipe-maintainers:
    - mortonjt
