{% set version = "1.0.2" %}
{% set name = "mmvec" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 398f75783e3ec98ae4026aeedd2bef416e0b4ac785048dd62ae6286785de865c


build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - qiime2.plugins = mmvec.q2.plugin_setup:plugin

requirements:
  host:
    - python >=3
    - pip

  run:
    - python >=3
    - pandas
    - click
    - tensorflow ==1.14.0
    - scikit-bio >0.5.4
    - seaborn
    - scikit-learn
    - tqdm
    - h5py
    - mock
    - biom-format

test:
  imports:
    - mmvec

about:
  home: https://github.com/biocore/mmvec
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Neural networks for microbe-metabolite interaction analysis'

extra:
  recipe-maintainers:
    - mortonjt
