{% set version = "1.0.4" %}
{% set name = "mmvec" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1f3c37b090ae4bc1c359dbf463622ab2c1bfef171744db405bf111413d5fc98d


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - qiime2.plugins = mmvec.q2.plugin_setup:plugin

requirements:
  host:
    - python >=3
    - pip

  run:
    - python >=3
    - pandas <1.0
    - click
    - tensorflow >=1.15,<2
    - scikit-bio >0.5.4
    - seaborn
    - numpy >1.13
    - scikit-learn
    - tqdm
    - h5py
    - mock
    - biom-format

test:
  imports:
    - mmvec

about:
  home: https://github.com/biocore/mmvec
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Neural networks for microbe-metabolite interaction analysis

extra:
  recipe-maintainers:
    - mortonjt
