travis:
  secure:
    BINSTAR_TOKEN: cFxqF7D78xw1OB4qfwCPMZG29tqaueHaK34xLLxdBH84tfwuUKm0dPvCc08aiPS17Djx4HlYTMwnril1o32VQd7HUPqZyzDVxeSRYUs6TmR4NQ5SGw8T4xyGvzQAHv65/aNC5whY5nvMErdrM5XQbPUFTlom7hUO4SNIYkMCMUjzwtXUJEcB7yfvItuVLyyhcHHqZ0c//MRVCPDRFAdXhdjufjM9aRdrulyucsNs+s2+g0tQI1sRf2mlYcTotXC4/BtSE8hKePZKPvNqPW2S2zWrz2V4Q6bqhRhIetBd9LEAXGUHwjwlbsPT181/X4cTUe+WEauGuDqWEJ3OXAWtCh8sf70g/QGuACxm502wFnBdWAdO6OBax6sy+Au1tGRTqpP4nLXJiQxkscxbxZvVYyUDGDHCgnuqpZ9FySEumgcJlYE/iOwlFHjiWLDFkPIARCuJH1MxEIqtX/MEMVj9r5w2pXunH8wSzYWLRTsosaRU3Ork83wu1PJ0+XAVtaSc5+LjOunxSClcTX0qlbj+cz5aWF9bBIe28hOcjWSctpQ57F4HbsK904m8eZq6dvTW/Nnmu0fDdbWeeLacAV8plb7JKLwE3wf7wHSeWfdKDRlgsLkYGvOfyq9LCt2iTXR9gptme5gKKvlcuJtUTCUksNviI7HMtgsn3xuyWlYlS+U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
